name: Michael Talley
favicon: null
layout_spectrum: 0.01142
typography_spectrum: 0.37702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#120806'
    - '#6e4426'
    - '#b3d2df'
    - '#a59c93'
  brandStrength: 0.37160802935250103
  lightness: 0.3763470225967467
  saturation: 0.01511019398458302
  rhythmicContrast: 0.14056312944740057
purpose: []
