name: Michael Talley
favicon: null
layout_spectrum: 0.15255
typography_spectrum: 0.37702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#d8d8d8'
    - '#bdbdbd'
    - '#4e4e4e'
    - '#737373'
  brandStrength: 0.37160802935250103
  lightness: 0.3763470225967467
  saturation: 0.01511019398458302
  rhythmicContrast: 0.14056312944740057
purpose: []
